name: compile
on:
  push:
    branches:
      - main
      - master
env:
  LATEX_ROOT: thesis-main
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Build latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: thesis-main.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape
        
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install
          npx semantic-release