name: compile
on:
  push:
    branches:
      - main
      - master
jobs:
  compile:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    concurrency:
      group: release
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          submodules: recursive
          
      - name: Compile latex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: thesis-main.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          npm install
          npx semantic-release
